### ISSUE TITLE
About DRS training

### ISSUE THREAD

**Issue by adf1178** [zhangyongshun/BagofTricks-LT#4]
Hello! Thanks for your contribution. I have  such questions:
The DRS strategy described in **Decoupling representation and classifier for long-tailed recognition** is that: first train whole network for 90 or 200 epochs, then freeze the backbone and re-initialize a classifier and train.  But the DRS strategy in the code is just to change a different sampler? or I just misunderstand the code?

**Comment by zhangyongshun** [comment]
Thanks for your question! 
"But the DRS strategy in the code is just to change a different sampler?": Yes, the DRS in our codes is just to change the sampler from the default sampler to a balanced sampler.
The details of DRS are firstly described in LDAM Loss (https://arxiv.org/pdf/1906.07413.pdf), and firstly introduced in Large Scale Fine-Grained Categorization and Domain-Specific Transfer Learning (https://arxiv.org/pdf/1806.06193.pdf), where the backbone is opened in the second stage in DRS. 
I think  Decoupling Representation shows another way to explore the balance between the backbone and classifier, and it is different with DRS. Besides, I think Decoupling Representation can be seen as a post-processing trick rather than a DRS method.

**Comment by adf1178** [comment]
> Thanks for your question!
> "But the DRS strategy in the code is just to change a different sampler?": Yes, the DRS in our codes is just to change the sampler from the default sampler to a balanced sampler.
> The details of DRS are firstly described in LDAM Loss (https://arxiv.org/pdf/1906.07413.pdf), and firstly introduced in Large Scale Fine-Grained Categorization and Domain-Specific Transfer Learning (https://arxiv.org/pdf/1806.06193.pdf), where the backbone is opened in the second stage in DRS.
> I think Decoupling Representation shows another way to explore the balance between the backbone and classifier, and it is different with DRS. Besides, I think Decoupling Representation can be seen as a post-processing trick rather than a DRS method.

Got it! Thanks again for your Patient and timely reply!
